# Generated by Django 4.2.11 on 2024-04-20 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnglishContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.CharField(max_length=255, verbose_name='About us')),
                ('projects', models.CharField(max_length=255, verbose_name='Projects')),
                ('works', models.CharField(max_length=255, verbose_name='Works')),
                ('team', models.CharField(max_length=255, verbose_name='Team')),
                ('contacts', models.CharField(max_length=255, verbose_name='Contacts')),
                ('hero_subtitle', models.TextField(verbose_name='Hero-subtitle')),
                ('hero_btn', models.CharField(max_length=50, verbose_name='Hero_btn')),
                ('who_subtitle', models.CharField(max_length=255, verbose_name='Who-subtitle')),
                ('who_p1', models.TextField(verbose_name='Who-p1')),
                ('who_p2', models.TextField(verbose_name='Who-p2')),
                ('who_p3', models.TextField(verbose_name='Who-p3')),
                ('projects_subtitle', models.CharField(max_length=255, verbose_name='Projects-subtitle')),
                ('projects_p1', models.TextField(default='', verbose_name='Projects-p1')),
                ('projects_p2', models.TextField(verbose_name='Projects-p2')),
                ('team_subtitle', models.CharField(max_length=255, verbose_name='Team-subtitle')),
                ('team_p1', models.TextField(verbose_name='Team-p1')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('is_published', models.BooleanField(default=True, verbose_name='Подтверждаю отправку')),
            ],
        ),
        migrations.CreateModel(
            name='Send_idea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('is_published', models.BooleanField(default=True, verbose_name='Подтверждаю отправку')),
            ],
        ),
    ]
